on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */1 * *"
name: check-libplanet-compatibility
jobs:
  check-libplanet-compatibility:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2019.1.0f2-windows-mono-0.9.0
    steps:
      - uses: actions/checkout@v2
      - run: .github/bin/bump_libplanet.sh
      - name: build
        run: .github/bin/build.sh
        env:
          ULF: "${{ secrets.ULF }}"
